# Generated by Django 5.2.7 on 2025-10-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balenciaga_app', '0002_size_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='commission_product',
            options={'verbose_name': 'Заказ-Товар', 'verbose_name_plural': 'Заказы-Товары'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='size_product',
            options={'verbose_name': 'Размер-Товар', 'verbose_name_plural': 'Размеры-Товары'},
        ),
        migrations.AlterField(
            model_name='commission',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=3),
        ),
    ]
