# Generated by Django 5.2.7 on 2025-10-24 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balenciaga_app', '0003_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balenciaga_app.product')),
            ],
            options={
                'verbose_name': 'Товар-Картина',
                'verbose_name_plural': 'Товары-Картины',
            },
        ),
    ]
