# Generated by Django 5.2.7 on 2025-10-08 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balenciaga_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balenciaga_app.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balenciaga_app.size')),
            ],
        ),
    ]
